### ISSUE TITLE
AUTH_FAILED

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn-old-repo-do-not-use#11]
1. the app works great from the google play
1. when I compile it(after building the JNI with no errors) the app does not connect to the VPN, and prints "AUTH_FAILED" on the logs.

**Comment by AlmogBaku** [comment]
works on `tags/v0.6.26-production` tag

**Comment by schwabe** [comment]
Do you have still problem with this?

**Comment by AlmogBaku** [comment]
@schwabe I'll try to use the master branch and will report you.
But i'm trying to understand what's going on with the new github repos.. can you please update us? haha :)

**Comment by AlmogBaku** [comment]
also, I'd love to help with the migration or anything else- feel free to reach me out

**Comment by schwabe** [comment]
google code is closing down.... the mercurial/git conversation is a total mess unfortenately. In doubt use the mercurial repository from code https://code.google.com/p/ics-openvpn/

**Comment by AlmogBaku** [comment]
Well, I guess it's a good thing that we're moving finally to use github as
the main origin! :)
anyway i'll try to do that ASAP and respond you

--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by AlmogBaku** [comment]
work on master
